M48
; DRILL file {KiCad 8.0.0} date 2024-03-10T19:40:47-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-10T19:40:47-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.924Y-3.336
X3.934Y-4.916
X5.754Y-3.586
X7.184Y-3.336
X7.184Y-4.926
M30
